# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-03 06:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=50, verbose_name='客户')),
                ('star', models.IntegerField(verbose_name='总体评价')),
                ('taste_score', models.IntegerField(verbose_name='口味')),
                ('environment_score', models.IntegerField(verbose_name='环境')),
                ('service_score', models.IntegerField(verbose_name='服务')),
                ('content', models.TextField(verbose_name='评价内容')),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('like', models.IntegerField(verbose_name='点赞数')),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='店名')),
                ('phone_number', models.CharField(max_length=50, verbose_name='电话')),
                ('star', models.IntegerField(default=0, verbose_name='星级')),
                ('address', models.TextField(default='', verbose_name='地址')),
                ('review_number', models.IntegerField(verbose_name='评论数')),
                ('area', models.CharField(default='', max_length=50, verbose_name='区域')),
                ('category', models.CharField(default='', max_length=50, verbose_name='类别')),
                ('per_consume', models.IntegerField(default=0, verbose_name='人均消费')),
                ('opening_time', models.CharField(default='', max_length=50, verbose_name='营业时间')),
                ('taste_score', models.FloatField(default=0.0, verbose_name='口味')),
                ('environment_score', models.FloatField(default=0.0, verbose_name='环境')),
                ('service_score', models.FloatField(default=0.0, verbose_name='服务')),
            ],
        ),
        migrations.AddField(
            model_name='review',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', related_query_name='review', to='store.Store'),
        ),
    ]
