# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-04 02:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='create_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
