# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-04 04:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20170704_1031'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='区域名')),
                ('state', models.BooleanField(default=False, verbose_name='状态')),
                ('num', models.BigIntegerField(default=0, verbose_name='数量')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='类型名')),
                ('state', models.BooleanField(default=False, verbose_name='状态')),
                ('num', models.BigIntegerField(default=0, verbose_name='数量')),
            ],
        ),
    ]
