# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-05 09:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_area_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='照片名')),
                ('img', models.ImageField(upload_to='photo')),
                ('path', models.FilePathField(path='photo')),
            ],
        ),
    ]
