# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-06 12:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='Idf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.TextField()),
                ('idf', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='StopWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='review',
            name='similarity',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='review',
            name='tfidf_info',
            field=models.TextField(default=''),
        ),
    ]
