# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-06 13:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20170706_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='similarity',
            field=models.FloatField(default=1.0),
        ),
    ]
