# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-07 07:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20170706_2128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='like_reviews',
        ),
        migrations.AddField(
            model_name='review',
            name='client',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', related_query_name='review', to='store.Client'),
            preserve_default=False,
        ),
    ]
